package ClienteP2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author ammy_
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("practica2sd?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        practica2sdPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("practica2sdPU").createEntityManager();
        divisasQuery = java.beans.Beans.isDesignTime() ? null : practica2sdPUEntityManager.createQuery("SELECT d.divisasNombre FROM Divisas d");
        divisasList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : divisasQuery.getResultList();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrameTurismo = new javax.swing.JInternalFrame();
        jTextFieldDivisa1 = new javax.swing.JTextField();
        jTextFieldDivisa2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButtonConvertir = new javax.swing.JButton();
        jLabelConvertirA = new javax.swing.JLabel();
        jInternalFrameGeograficos = new javax.swing.JInternalFrame();
        jInternalFrameEyC = new javax.swing.JInternalFrame();
        jInternalFrameOtros = new javax.swing.JInternalFrame();
        jLabelServicios = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrameTurismo.setVisible(true);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, divisasQuery, eLProperty, jComboBox2);
        bindingGroup.addBinding(jComboBoxBinding);

        jButtonConvertir.setText("Convertir");

        jLabelConvertirA.setText("a");

        javax.swing.GroupLayout jInternalFrameTurismoLayout = new javax.swing.GroupLayout(jInternalFrameTurismo.getContentPane());
        jInternalFrameTurismo.getContentPane().setLayout(jInternalFrameTurismoLayout);
        jInternalFrameTurismoLayout.setHorizontalGroup(
            jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jTextFieldDivisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelConvertirA, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldDivisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButtonConvertir)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jInternalFrameTurismoLayout.setVerticalGroup(
            jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDivisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDivisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConvertir)
                    .addComponent(jLabelConvertirA))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Turismo", jInternalFrameTurismo);

        jInternalFrameGeograficos.setVisible(true);

        javax.swing.GroupLayout jInternalFrameGeograficosLayout = new javax.swing.GroupLayout(jInternalFrameGeograficos.getContentPane());
        jInternalFrameGeograficos.getContentPane().setLayout(jInternalFrameGeograficosLayout);
        jInternalFrameGeograficosLayout.setHorizontalGroup(
            jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrameGeograficosLayout.setVerticalGroup(
            jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Geográficos", jInternalFrameGeograficos);

        jInternalFrameEyC.setVisible(true);

        javax.swing.GroupLayout jInternalFrameEyCLayout = new javax.swing.GroupLayout(jInternalFrameEyC.getContentPane());
        jInternalFrameEyC.getContentPane().setLayout(jInternalFrameEyCLayout);
        jInternalFrameEyCLayout.setHorizontalGroup(
            jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrameEyCLayout.setVerticalGroup(
            jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Entretenimiento y Cultura", jInternalFrameEyC);

        jInternalFrameOtros.setVisible(true);

        javax.swing.GroupLayout jInternalFrameOtrosLayout = new javax.swing.GroupLayout(jInternalFrameOtros.getContentPane());
        jInternalFrameOtros.getContentPane().setLayout(jInternalFrameOtrosLayout);
        jInternalFrameOtrosLayout.setHorizontalGroup(
            jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrameOtrosLayout.setVerticalGroup(
            jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Otros", jInternalFrameOtros);

        jLabelServicios.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelServicios.setText("Servicios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabelServicios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelServicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<ClienteP2.Divisas> divisasList;
    private javax.persistence.Query divisasQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButtonConvertir;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JInternalFrame jInternalFrameEyC;
    private javax.swing.JInternalFrame jInternalFrameGeograficos;
    private javax.swing.JInternalFrame jInternalFrameOtros;
    private javax.swing.JInternalFrame jInternalFrameTurismo;
    private javax.swing.JLabel jLabelConvertirA;
    private javax.swing.JLabel jLabelServicios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldDivisa1;
    private javax.swing.JTextField jTextFieldDivisa2;
    private javax.persistence.EntityManager practica2sdPUEntityManager;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
