package Proyecto2;

import java.rmi.Naming;
import java.util.ArrayList;
import java.util.Vector;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author ammy_
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrameTurismo = new javax.swing.JInternalFrame();
        jTextFieldDivisa1 = new javax.swing.JTextField();
        jTextFieldDivisa2 = new javax.swing.JTextField();
        jButtonConvertir = new javax.swing.JButton();
        jLabelConvertirA = new javax.swing.JLabel();
        jComboBoxDivisa1 = new javax.swing.JComboBox<>();
        jLabelConversorDivisas = new javax.swing.JLabel();
        jComboBoxDivisa2 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelClima = new javax.swing.JLabel();
        jComboBoxCiudades = new javax.swing.JComboBox<>();
        jLabelGradosC = new javax.swing.JLabel();
        jLabelInfoCiudad = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneTemperatura = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPaneHora = new javax.swing.JTextPane();
        jInternalFrameGeograficos = new javax.swing.JInternalFrame();
        jLabelUbicacion = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jTextFieldUbicacion = new javax.swing.JTextField();
        jScrollPaneUbicacion = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabelDatosProfesor = new javax.swing.JLabel();
        jLabelNombreProfesor = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelCubiculo = new javax.swing.JLabel();
        jTextFieldNombreProfesor = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPaneTelefono = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPaneCorreo = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPaneCubiculo = new javax.swing.JTextPane();
        jButtonUbicar = new javax.swing.JButton();
        jButtonDatos = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jListMaterias = new javax.swing.JList<>();
        jInternalFrameEyC = new javax.swing.JInternalFrame();
        jComboBoxPeliculas = new javax.swing.JComboBox<>();
        jLabelPelicula = new javax.swing.JLabel();
        jLabelPeliculas = new javax.swing.JLabel();
        jLabelMuseos = new javax.swing.JLabel();
        jLabelTeatro = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableCineHorario = new javax.swing.JTable();
        jComboBoxMuseos = new javax.swing.JComboBox<>();
        jScrollHorarioMuseo = new javax.swing.JScrollPane();
        jTextPaneMuseos = new javax.swing.JTextPane();
        jComboBoxTeatro = new javax.swing.JComboBox<>();
        jLabelObra = new javax.swing.JLabel();
        jLabelMuseo = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPaneTeatro = new javax.swing.JTextPane();
        jInternalFrameOtros = new javax.swing.JInternalFrame();
        jTextFieldMontoPropina = new javax.swing.JTextField();
        jTextFieldMontoDescuento = new javax.swing.JTextField();
        jLabelPropinas = new javax.swing.JLabel();
        jLabelDescuentos = new javax.swing.JLabel();
        jLabelIntereses = new javax.swing.JLabel();
        jTextFieldMontoInteres = new javax.swing.JTextField();
        jTextFieldInteres = new javax.swing.JTextField();
        jComboBoxPorcentajePropina = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jTextFieldPorcentajedescuento = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPanePropina = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextPaneDescuento = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextPaneInteres = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextPaneMontoInteres = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonTotalPropina = new javax.swing.JButton();
        jButtonTotalDescuento = new javax.swing.JButton();
        jButtonTotalInteres = new javax.swing.JButton();
        jLabelServicios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrameTurismo.setVisible(true);

        jTextFieldDivisa1.setText("Cantidad");

        jTextFieldDivisa2.setText("Cantidad");

        jButtonConvertir.setText("Convertir");
        jButtonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirActionPerformed(evt);
            }
        });

        jLabelConvertirA.setText("a");

        jComboBoxDivisa1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "MXN", "EUR", "GBP" }));
        jComboBoxDivisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDivisa1ActionPerformed(evt);
            }
        });

        jLabelConversorDivisas.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabelConversorDivisas.setText("Conversor de Divisas");

        jComboBoxDivisa2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "MXN", "EUR", "GBP" }));

        jLabelClima.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jLabelClima.setText("Clima");

        jComboBoxCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCiudadesActionPerformed(evt);
            }
        });

        jLabelGradosC.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabelGradosC.setText("ºC");

        jLabelInfoCiudad.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabelInfoCiudad.setText("Información de Ciudades");

        jLabelHora.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jLabelHora.setText("Hora");

        jTextPaneTemperatura.setText("Temperatura");
        jScrollPane2.setViewportView(jTextPaneTemperatura);

        jTextPaneHora.setText("Hora");
        jScrollPane3.setViewportView(jTextPaneHora);

        javax.swing.GroupLayout jInternalFrameTurismoLayout = new javax.swing.GroupLayout(jInternalFrameTurismo.getContentPane());
        jInternalFrameTurismo.getContentPane().setLayout(jInternalFrameTurismoLayout);
        jInternalFrameTurismoLayout.setHorizontalGroup(
            jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldDivisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jComboBoxDivisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelConvertirA, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxDivisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jTextFieldDivisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonConvertir)
                .addGap(23, 23, 23))
            .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                        .addComponent(jLabelClima)
                        .addContainerGap(473, Short.MAX_VALUE))
                    .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGradosC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))))
            .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                .addGroup(jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelHora)
                            .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                                .addComponent(jLabelInfoCiudad)
                                .addGap(42, 42, 42))))
                    .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelConversorDivisas))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrameTurismoLayout.setVerticalGroup(
            jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConversorDivisas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDivisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDivisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConvertir)
                    .addComponent(jLabelConvertirA)
                    .addComponent(jComboBoxDivisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDivisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInfoCiudad)
                .addGap(25, 25, 25)
                .addComponent(jComboBoxCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHora, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelClima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGradosC))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Turismo", jInternalFrameTurismo);

        jInternalFrameGeograficos.setVisible(true);

        jLabelUbicacion.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabelUbicacion.setText("Ubicación de Espacio Físico");

        jTextFieldUbicacion.setText("Escriba el nombre del Edificio");

        jTextPane1.setText("Ubicacion");
        jScrollPaneUbicacion.setViewportView(jTextPane1);

        jLabelDatosProfesor.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabelDatosProfesor.setText("Datos del Profesor");

        jLabelNombreProfesor.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabelNombreProfesor.setText("Nombre");

        jLabelTelefono.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabelTelefono.setText("Teléfono:");

        jLabelCorreo.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabelCorreo.setText("Correo:");

        jLabelCubiculo.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabelCubiculo.setText("Cubículo:");

        jTextFieldNombreProfesor.setText("Escriba el nombre del Profesor");

        jTextPaneTelefono.setText("Numero");
        jScrollPane4.setViewportView(jTextPaneTelefono);

        jTextPaneCorreo.setText("nombre@dominio.com");
        jScrollPane5.setViewportView(jTextPaneCorreo);

        jTextPaneCubiculo.setText("Ubicación");
        jScrollPane6.setViewportView(jTextPaneCubiculo);

        jButtonUbicar.setText("Ubicar");

        jButtonDatos.setText("Obtener");
        jButtonDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDatosActionPerformed(evt);
            }
        });

        jListMaterias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Materia 1", "Materia 2", "Materia 3", "Materia 4", "Materia 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(jListMaterias);

        javax.swing.GroupLayout jInternalFrameGeograficosLayout = new javax.swing.GroupLayout(jInternalFrameGeograficos.getContentPane());
        jInternalFrameGeograficos.getContentPane().setLayout(jInternalFrameGeograficosLayout);
        jInternalFrameGeograficosLayout.setHorizontalGroup(
            jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameGeograficosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4))
                    .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                        .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabelUbicacion))
                            .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                                        .addComponent(jTextFieldUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonUbicar))
                                    .addComponent(jScrollPaneUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(jLabelDatosProfesor))
                            .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNombreProfesor)
                                    .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                                        .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldNombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                                                .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                                                        .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabelTelefono)
                                                            .addComponent(jLabelCorreo))
                                                        .addGap(19, 19, 19))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameGeograficosLayout.createSequentialGroup()
                                                        .addComponent(jLabelCubiculo)
                                                        .addGap(18, 18, 18)))
                                                .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jScrollPane6)
                                                    .addComponent(jScrollPane5)
                                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonDatos)))))
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jInternalFrameGeograficosLayout.setVerticalGroup(
            jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUbicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUbicar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDatosProfesor)
                .addGap(18, 18, 18)
                .addComponent(jLabelNombreProfesor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                            .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                                    .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelTelefono)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelCorreo))
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabelCubiculo)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Geográficos", jInternalFrameGeograficos);

        jInternalFrameEyC.setVisible(true);

        jLabelPelicula.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabelPelicula.setText("Película:");

        jLabelPeliculas.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabelPeliculas.setText("Películas");

        jLabelMuseos.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabelMuseos.setText("Museos");

        jLabelTeatro.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabelTeatro.setText("Teatro");

        jTableCineHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cine", "Horarios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTableCineHorario);

        jTextPaneMuseos.setText("Horario del museo");
        jScrollHorarioMuseo.setViewportView(jTextPaneMuseos);

        jLabelObra.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabelObra.setText("Obra:");

        jLabelMuseo.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabelMuseo.setText("Museo:");

        jTextPaneTeatro.setText("Costo de la obra");
        jScrollPane9.setViewportView(jTextPaneTeatro);

        javax.swing.GroupLayout jInternalFrameEyCLayout = new javax.swing.GroupLayout(jInternalFrameEyC.getContentPane());
        jInternalFrameEyC.getContentPane().setLayout(jInternalFrameEyCLayout);
        jInternalFrameEyCLayout.setHorizontalGroup(
            jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jScrollHorarioMuseo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                .addGroup(jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameEyCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                        .addGroup(jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabelPelicula)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(jLabelObra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxTeatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameEyCLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabelMuseo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxMuseos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                .addGroup(jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabelPeliculas))
                    .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabelMuseos))
                    .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabelTeatro))
                    .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jInternalFrameEyCLayout.setVerticalGroup(
            jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPeliculas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPelicula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabelMuseos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMuseos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMuseo))
                .addGap(7, 7, 7)
                .addComponent(jScrollHorarioMuseo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTeatro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTeatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelObra))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Entretenimiento y Cultura", jInternalFrameEyC);

        jInternalFrameOtros.setVisible(true);

        jTextFieldMontoPropina.setText("Monto");

        jTextFieldMontoDescuento.setText("Monto");

        jLabelPropinas.setText("Propinas");

        jLabelDescuentos.setText("Descuentos");

        jLabelIntereses.setText("Intereses");

        jTextFieldMontoInteres.setText("Monto");

        jTextFieldInteres.setText("Interes");

        jComboBoxPorcentajePropina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10%", "15%", "20%" }));

        jTextFieldPorcentajedescuento.setText("Porcentaje");

        jTextPanePropina.setText("Total");
        jScrollPane7.setViewportView(jTextPanePropina);

        jTextPaneDescuento.setText("Total");
        jScrollPane11.setViewportView(jTextPaneDescuento);

        jTextPaneInteres.setText("Total");
        jScrollPane12.setViewportView(jTextPaneInteres);

        jTextPaneMontoInteres.setText("Monto de interes");
        jScrollPane13.setViewportView(jTextPaneMontoInteres);

        jLabel1.setText("Monto");

        jLabel2.setText("Porcentaje");

        jLabel3.setText("Total a pagar");

        jLabel4.setText("Monto");

        jLabel5.setText("Porciento de descuento");

        jLabel6.setText("Total a pagar");

        jLabel7.setText("Adeudo");

        jLabel8.setText("Porcentaje de interes");

        jLabel9.setText("Adeudo de intereses");

        jLabel10.setText("Total a pagar");

        jButtonTotalPropina.setText("Total");

        jButtonTotalDescuento.setText("Total");

        jButtonTotalInteres.setText("Total");

        javax.swing.GroupLayout jInternalFrameOtrosLayout = new javax.swing.GroupLayout(jInternalFrameOtros.getContentPane());
        jInternalFrameOtros.getContentPane().setLayout(jInternalFrameOtrosLayout);
        jInternalFrameOtrosLayout.setHorizontalGroup(
            jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                        .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3))
                        .addContainerGap())
                    .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldMontoInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextFieldMontoPropina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90)
                                .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                        .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jComboBoxPorcentajePropina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(78, 78, 78)
                                        .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabelDescuentos))))
                            .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMontoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(jLabel5))
                                    .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelIntereses)
                                            .addComponent(jTextFieldPorcentajedescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(59, 59, 59)
                                .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel8))
                                    .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(jTextFieldInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)
                                .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10))))
                        .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameOtrosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(jButtonTotalDescuento)
                                .addGap(49, 49, 49))
                            .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jButtonTotalPropina))
                                    .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jButtonTotalInteres)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabelPropinas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrameOtrosLayout.setVerticalGroup(
            jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonTotalInteres)
                    .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                        .addComponent(jLabelPropinas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(3, 3, 3)
                                .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldMontoPropina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxPorcentajePropina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonTotalPropina))
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addComponent(jLabelDescuentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jInternalFrameOtrosLayout.createSequentialGroup()
                                        .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldPorcentajedescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldMontoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabelIntereses)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrameOtrosLayout.createSequentialGroup()
                                        .addComponent(jButtonTotalDescuento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldMontoInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Otros", jInternalFrameOtros);

        jLabelServicios.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabelServicios.setText("Servicios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabelServicios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelServicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCiudadesActionPerformed
       // System.out.println("HOLA");
        jTextPaneHora.setText("Hola");
    }//GEN-LAST:event_jComboBoxCiudadesActionPerformed

    private void jButtonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirActionPerformed
        //Checar que el combo box si esté seleccionado
        int divisa1 = jComboBoxDivisa1.getSelectedIndex();
        int divisa2 = jComboBoxDivisa2.getSelectedIndex();
        
        //Checar que la cantidad sea numerica
        double cantidad = Double.parseDouble(jTextFieldDivisa1.getText());
        
        //Turismo	
        try {
            ITurismo turismo;
            turismo = (ITurismo)Naming.lookup("rmi://localhost:1099/Turismo");
            jTextFieldDivisa2.setText(String.valueOf(turismo.convertirDivisa(divisa1+1, cantidad, divisa2+1)));
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_jButtonConvertirActionPerformed

    private void jComboBoxDivisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDivisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDivisa1ActionPerformed

    private void jButtonDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDatosActionPerformed
        String profesor = jTextFieldNombreProfesor.getText();
        IGeografico geografico;
        try {
            geografico = (IGeografico)Naming.lookup("rmi://localhost:1099/Geografico");
            Profesor prof = geografico.getDatosProfesor(profesor);
            Vector<String> mensaje = new Vector<String>();
            if(prof == null){
                jTextPaneTelefono.setText("Profesor no encontrado");
                jTextPaneCorreo.setText("Profesor no encontrado");
                jTextPaneCubiculo.setText("Profesor no encontrado");
                mensaje.addElement("Profesor no encontrado");
                jListMaterias.setListData(mensaje);
            }else{
                jTextFieldNombreProfesor.setText(prof.getNombre());
                jTextPaneTelefono.setText(prof.getTelefono());
                jTextPaneCorreo.setText(prof.getCorreo());
                jTextPaneCubiculo.setText(prof.getCubiculo());
                
                
                ArrayList<String> ueas = geografico.materiasImpartidas(profesor);
                if(ueas.isEmpty()){
                    mensaje.addElement("No ha impartido uea");
                    jListMaterias.setListData(mensaje);
                }else{
                    String[] array = new String[ueas.size()];
                    jListMaterias.setListData(ueas.toArray(array));
                }
                
            }                  
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConvertir;
    private javax.swing.JButton jButtonDatos;
    private javax.swing.JButton jButtonTotalDescuento;
    private javax.swing.JButton jButtonTotalInteres;
    private javax.swing.JButton jButtonTotalPropina;
    private javax.swing.JButton jButtonUbicar;
    private javax.swing.JComboBox<String> jComboBoxCiudades;
    private javax.swing.JComboBox<String> jComboBoxDivisa1;
    private javax.swing.JComboBox<String> jComboBoxDivisa2;
    private javax.swing.JComboBox<String> jComboBoxMuseos;
    private javax.swing.JComboBox<String> jComboBoxPeliculas;
    private javax.swing.JComboBox<String> jComboBoxPorcentajePropina;
    private javax.swing.JComboBox<String> jComboBoxTeatro;
    private javax.swing.JInternalFrame jInternalFrameEyC;
    private javax.swing.JInternalFrame jInternalFrameGeograficos;
    private javax.swing.JInternalFrame jInternalFrameOtros;
    private javax.swing.JInternalFrame jInternalFrameTurismo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClima;
    private javax.swing.JLabel jLabelConversorDivisas;
    private javax.swing.JLabel jLabelConvertirA;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelCubiculo;
    private javax.swing.JLabel jLabelDatosProfesor;
    private javax.swing.JLabel jLabelDescuentos;
    private javax.swing.JLabel jLabelGradosC;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelInfoCiudad;
    private javax.swing.JLabel jLabelIntereses;
    private javax.swing.JLabel jLabelMuseo;
    private javax.swing.JLabel jLabelMuseos;
    private javax.swing.JLabel jLabelNombreProfesor;
    private javax.swing.JLabel jLabelObra;
    private javax.swing.JLabel jLabelPelicula;
    private javax.swing.JLabel jLabelPeliculas;
    private javax.swing.JLabel jLabelPropinas;
    private javax.swing.JLabel jLabelServicios;
    private javax.swing.JLabel jLabelTeatro;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelUbicacion;
    private javax.swing.JList<String> jListMaterias;
    private javax.swing.JScrollPane jScrollHorarioMuseo;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JScrollPane jScrollPaneUbicacion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCineHorario;
    private javax.swing.JTextField jTextFieldDivisa1;
    private javax.swing.JTextField jTextFieldDivisa2;
    private javax.swing.JTextField jTextFieldInteres;
    private javax.swing.JTextField jTextFieldMontoDescuento;
    private javax.swing.JTextField jTextFieldMontoInteres;
    private javax.swing.JTextField jTextFieldMontoPropina;
    private javax.swing.JTextField jTextFieldNombreProfesor;
    private javax.swing.JTextField jTextFieldPorcentajedescuento;
    private javax.swing.JTextField jTextFieldUbicacion;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPaneCorreo;
    private javax.swing.JTextPane jTextPaneCubiculo;
    private javax.swing.JTextPane jTextPaneDescuento;
    private javax.swing.JTextPane jTextPaneHora;
    private javax.swing.JTextPane jTextPaneInteres;
    private javax.swing.JTextPane jTextPaneMontoInteres;
    private javax.swing.JTextPane jTextPaneMuseos;
    private javax.swing.JTextPane jTextPanePropina;
    private javax.swing.JTextPane jTextPaneTeatro;
    private javax.swing.JTextPane jTextPaneTelefono;
    private javax.swing.JTextPane jTextPaneTemperatura;
    // End of variables declaration//GEN-END:variables
}
