package Proyecto2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author ammy_
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("practica2sd?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        practica2sdPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("practica2sdPU").createEntityManager();
        divisasQuery = java.beans.Beans.isDesignTime() ? null : practica2sdPUEntityManager.createQuery("SELECT d.divisasNombre FROM Divisas d");
        divisasList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : divisasQuery.getResultList();
        ciudadQuery = java.beans.Beans.isDesignTime() ? null : practica2sdPUEntityManager.createQuery("SELECT c.ciudadNombre FROM Ciudad c");
        ciudadList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : ciudadQuery.getResultList();
        ciudadQuery1 = java.beans.Beans.isDesignTime() ? null : practica2sdPUEntityManager.createQuery("SELECT c.ciudadClima FROM Ciudad c WHERE c.ciudadNombre = 'Paris'");
        ciudadList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : ciudadQuery1.getResultList();
        peliculaQuery = java.beans.Beans.isDesignTime() ? null : practica2sdPUEntityManager.createQuery("SELECT p.peliculaNombre FROM Pelicula p");
        peliculaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : peliculaQuery.getResultList();
        museoQuery = java.beans.Beans.isDesignTime() ? null : practica2sdPUEntityManager.createQuery("SELECT m.museoNombre FROM Museo m");
        museoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : museoQuery.getResultList();
        obraQuery = java.beans.Beans.isDesignTime() ? null : practica2sdPUEntityManager.createQuery("SELECT o.obraNombre FROM Obra o");
        obraList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : obraQuery.getResultList();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrameTurismo = new javax.swing.JInternalFrame();
        jTextFieldDivisa1 = new javax.swing.JTextField();
        jTextFieldDivisa2 = new javax.swing.JTextField();
        jButtonConvertir = new javax.swing.JButton();
        jLabelConvertirA = new javax.swing.JLabel();
        jComboBoxDivisa2 = new javax.swing.JComboBox<>();
        jLabelConversorDivisas = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelClima = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabelGradosC = new javax.swing.JLabel();
        jLabelInfoCiudad = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneClima = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jInternalFrameGeograficos = new javax.swing.JInternalFrame();
        jLabelUbicacion = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jTextFieldUbicacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabelDatosProfesor = new javax.swing.JLabel();
        jLabelNombreProfesor = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelCubiculo = new javax.swing.JLabel();
        jTextFieldNombreProfesor = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPaneTelefono = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPaneCorreo = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPaneCubiculo = new javax.swing.JTextPane();
        jButtonUbicar = new javax.swing.JButton();
        jInternalFrameEyC = new javax.swing.JInternalFrame();
        jComboBoxPeliculas = new javax.swing.JComboBox<>();
        jLabelPelicula = new javax.swing.JLabel();
        jLabelPeliculas = new javax.swing.JLabel();
        jLabelMuseos = new javax.swing.JLabel();
        jLabelTeatro = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableCineHorario = new javax.swing.JTable();
        jComboBoxMuseos = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPaneMuseos = new javax.swing.JTextPane();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabelObra = new javax.swing.JLabel();
        jLabelMuseo = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextPaneTeatro = new javax.swing.JTextPane();
        jInternalFrameOtros = new javax.swing.JInternalFrame();
        jLabelServicios = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrameTurismo.setVisible(true);

        jButtonConvertir.setText("Convertir");

        jLabelConvertirA.setText("a");

        jComboBoxDivisa2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, divisasQuery, eLProperty, jComboBoxDivisa2);
        bindingGroup.addBinding(jComboBoxBinding);

        jLabelConversorDivisas.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabelConversorDivisas.setText("Conversor de Divisas");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, divisasQuery, eLProperty, jComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);

        jLabelClima.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jLabelClima.setText("Clima");

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, ciudadQuery, eLProperty, jComboBox2);
        bindingGroup.addBinding(jComboBoxBinding);

        jLabelGradosC.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabelGradosC.setText("ºC");

        jLabelInfoCiudad.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabelInfoCiudad.setText("Información de Ciudades");

        jLabelHora.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jLabelHora.setText("Hora");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, ciudadQuery1, org.jdesktop.beansbinding.ELProperty.create("${singleResult}"), jTextPaneClima, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(jTextPaneClima);

        jScrollPane3.setViewportView(jTextPane2);

        javax.swing.GroupLayout jInternalFrameTurismoLayout = new javax.swing.GroupLayout(jInternalFrameTurismo.getContentPane());
        jInternalFrameTurismo.getContentPane().setLayout(jInternalFrameTurismoLayout);
        jInternalFrameTurismoLayout.setHorizontalGroup(
            jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jTextFieldDivisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jComboBoxDivisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelConvertirA, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jTextFieldDivisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonConvertir)
                .addGap(94, 94, 94))
            .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                        .addComponent(jLabelClima)
                        .addContainerGap(434, Short.MAX_VALUE))
                    .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGradosC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))))
            .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                .addGroup(jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelHora)
                        .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                            .addGap(191, 191, 191)
                            .addComponent(jLabelInfoCiudad)
                            .addGap(42, 42, 42)))
                    .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelConversorDivisas))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrameTurismoLayout.setVerticalGroup(
            jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameTurismoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConversorDivisas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDivisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDivisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConvertir)
                    .addComponent(jLabelConvertirA)
                    .addComponent(jComboBoxDivisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInfoCiudad)
                .addGap(25, 25, 25)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClima)
                    .addComponent(jLabelHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameTurismoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGradosC))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Turismo", jInternalFrameTurismo);

        jInternalFrameGeograficos.setVisible(true);

        jLabelUbicacion.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabelUbicacion.setText("Ubicación de Espacio Físico");

        jTextFieldUbicacion.setText("Escriba el nombre del Edificio");

        jScrollPane1.setViewportView(jTextPane1);

        jLabelDatosProfesor.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabelDatosProfesor.setText("Datos del Profesor");

        jLabelNombreProfesor.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabelNombreProfesor.setText("Nombre");

        jLabelTelefono.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabelTelefono.setText("Teléfono:");

        jLabelCorreo.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabelCorreo.setText("Correo:");

        jLabelCubiculo.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabelCubiculo.setText("Cubículo:");

        jTextFieldNombreProfesor.setText("Escriba el nombre del Profesor");

        jScrollPane4.setViewportView(jTextPaneTelefono);

        jScrollPane5.setViewportView(jTextPaneCorreo);

        jScrollPane6.setViewportView(jTextPaneCubiculo);

        jButtonUbicar.setText("Ubicar");

        javax.swing.GroupLayout jInternalFrameGeograficosLayout = new javax.swing.GroupLayout(jInternalFrameGeograficos.getContentPane());
        jInternalFrameGeograficos.getContentPane().setLayout(jInternalFrameGeograficosLayout);
        jInternalFrameGeograficosLayout.setHorizontalGroup(
            jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameGeograficosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4))
                    .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                        .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabelUbicacion))
                            .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                                        .addComponent(jTextFieldUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonUbicar))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(jLabelDatosProfesor)))
                        .addGap(0, 112, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreProfesor)
                    .addComponent(jTextFieldNombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                        .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                                .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTelefono)
                                    .addComponent(jLabelCorreo))
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameGeograficosLayout.createSequentialGroup()
                                .addComponent(jLabelCubiculo)
                                .addGap(18, 18, 18)))
                        .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrameGeograficosLayout.setVerticalGroup(
            jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUbicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUbicar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                        .addComponent(jLabelDatosProfesor)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNombreProfesor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                                .addGroup(jInternalFrameGeograficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jInternalFrameGeograficosLayout.createSequentialGroup()
                                        .addComponent(jTextFieldNombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelTelefono))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCorreo))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelCubiculo))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Geográficos", jInternalFrameGeograficos);

        jInternalFrameEyC.setVisible(true);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, peliculaQuery, eLProperty, jComboBoxPeliculas);
        bindingGroup.addBinding(jComboBoxBinding);

        jLabelPelicula.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabelPelicula.setText("Película:");

        jLabelPeliculas.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabelPeliculas.setText("Películas");

        jLabelMuseos.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabelMuseos.setText("Museos");

        jLabelTeatro.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jLabelTeatro.setText("Teatro");

        jTableCineHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cine", "Horarios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTableCineHorario);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, museoQuery, eLProperty, jComboBoxMuseos);
        bindingGroup.addBinding(jComboBoxBinding);

        jScrollPane7.setViewportView(jTextPaneMuseos);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, obraQuery, eLProperty, jComboBox3);
        bindingGroup.addBinding(jComboBoxBinding);

        jLabelObra.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabelObra.setText("Obra:");

        jLabelMuseo.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabelMuseo.setText("Museo:");

        jScrollPane9.setViewportView(jTextPaneTeatro);

        javax.swing.GroupLayout jInternalFrameEyCLayout = new javax.swing.GroupLayout(jInternalFrameEyC.getContentPane());
        jInternalFrameEyC.getContentPane().setLayout(jInternalFrameEyCLayout);
        jInternalFrameEyCLayout.setHorizontalGroup(
            jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                .addGroup(jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameEyCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                        .addGroup(jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabelPelicula)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(jLabelObra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameEyCLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabelMuseo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxMuseos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                .addGroup(jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabelPeliculas))
                    .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabelMuseos))
                    .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabelTeatro))
                    .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jInternalFrameEyCLayout.setVerticalGroup(
            jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameEyCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPeliculas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPelicula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabelMuseos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMuseos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMuseo))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTeatro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameEyCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelObra))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Entretenimiento y Cultura", jInternalFrameEyC);

        jInternalFrameOtros.setVisible(true);

        javax.swing.GroupLayout jInternalFrameOtrosLayout = new javax.swing.GroupLayout(jInternalFrameOtros.getContentPane());
        jInternalFrameOtros.getContentPane().setLayout(jInternalFrameOtrosLayout);
        jInternalFrameOtrosLayout.setHorizontalGroup(
            jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        jInternalFrameOtrosLayout.setVerticalGroup(
            jInternalFrameOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Otros", jInternalFrameOtros);

        jLabelServicios.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabelServicios.setText("Servicios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelServicios)
                .addGap(236, 236, 236))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelServicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<Proyecto2.Ciudad> ciudadList;
    private java.util.List<Proyecto2.Ciudad> ciudadList1;
    private javax.persistence.Query ciudadQuery;
    private javax.persistence.Query ciudadQuery1;
    private java.util.List<Proyecto2.Divisas> divisasList;
    private javax.persistence.Query divisasQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButtonConvertir;
    private javax.swing.JButton jButtonUbicar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBoxDivisa2;
    private javax.swing.JComboBox<String> jComboBoxMuseos;
    private javax.swing.JComboBox<String> jComboBoxPeliculas;
    private javax.swing.JInternalFrame jInternalFrameEyC;
    private javax.swing.JInternalFrame jInternalFrameGeograficos;
    private javax.swing.JInternalFrame jInternalFrameOtros;
    private javax.swing.JInternalFrame jInternalFrameTurismo;
    private javax.swing.JLabel jLabelClima;
    private javax.swing.JLabel jLabelConversorDivisas;
    private javax.swing.JLabel jLabelConvertirA;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelCubiculo;
    private javax.swing.JLabel jLabelDatosProfesor;
    private javax.swing.JLabel jLabelGradosC;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelInfoCiudad;
    private javax.swing.JLabel jLabelMuseo;
    private javax.swing.JLabel jLabelMuseos;
    private javax.swing.JLabel jLabelNombreProfesor;
    private javax.swing.JLabel jLabelObra;
    private javax.swing.JLabel jLabelPelicula;
    private javax.swing.JLabel jLabelPeliculas;
    private javax.swing.JLabel jLabelServicios;
    private javax.swing.JLabel jLabelTeatro;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelUbicacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCineHorario;
    private javax.swing.JTextField jTextFieldDivisa1;
    private javax.swing.JTextField jTextFieldDivisa2;
    private javax.swing.JTextField jTextFieldNombreProfesor;
    private javax.swing.JTextField jTextFieldUbicacion;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPaneClima;
    private javax.swing.JTextPane jTextPaneCorreo;
    private javax.swing.JTextPane jTextPaneCubiculo;
    private javax.swing.JTextPane jTextPaneMuseos;
    private javax.swing.JTextPane jTextPaneTeatro;
    private javax.swing.JTextPane jTextPaneTelefono;
    private java.util.List<Proyecto2.Museo> museoList;
    private javax.persistence.Query museoQuery;
    private java.util.List<Proyecto2.Obra> obraList;
    private javax.persistence.Query obraQuery;
    private java.util.List<Proyecto2.Pelicula> peliculaList;
    private javax.persistence.Query peliculaQuery;
    private javax.persistence.EntityManager practica2sdPUEntityManager;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
